FROM node:16.16.0-alpine3.15

ENV NODE_ENV=production
EXPOSE 3001

COPY ./backend/dist /code/backend/dist
COPY ./backend/package.json /code/backend/package.json
COPY ./package.json /code

WORKDIR /code
RUN npm install

CMD [ "node", "/code/backend/dist/index.js" ]
